---
- name: Install required PHP extensions for Matomo
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ matomo_php_extensions }}"
  notify: reload php-fpm

- name: Install PyMySQL
  apt:
    name: python3-pymysql
    state: present
  become: yes

- name: Check if Matomo variables are set for each site
  fail:
    msg: >
      Matomo database credentials are not properly set for the site '{{ item.key }}'. 
      Please ensure that the following variables are configured:
      - matomo.db
      - matomo.db.user
      - matomo.db.password
      - matomo.paths
      - matomo.paths.addons
      - matomo.paths.matomo
  when:
    - item.value.matomo is not defined or
      item.value.matomo.db is not defined or
      item.value.matomo.db.user is not defined or
      item.value.matomo.db.password is not defined or
      item.value.matomo.paths is not defined or
      item.value.matomo.paths.addons is not defined or
      item.value.matomo.paths.matomo is not defined
  with_dict: "{{ combined_wordpress_sites }}"
  no_log: "{{ item.value.matomo.db.password is not defined }}"
  tags: matomo

- name: Create addons folder for Matomo installation
  file:
    path: "{{ addons_dir }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
  with_dict: "{{ wordpress_sites }}"
  no_log: true

- name: Check if Matomo is already installed
  stat:
    path: "{{ addons_dir }}/matomo/config/config.ini.php"
  register: matomo_config_check
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Check if Matomo database exists
  mysql_db:
    name: "{{ matomo_db_name }}"
    state: present
    login_host: "{{ site_env.db_host }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    login_port: "{{ mysql_port | default('3306') }}"
  check_mode: yes
  register: matomo_db
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Download Matomo
  get_url:
    url: "{{ matomo_url }}"
    dest: "/tmp/matomo_latest.zip"
  when: not (matomo_config_check.results | map(attribute='stat.exists') | select('true') | list | length > 0)
  tags: matomo

- name: Unzip Matomo
  unarchive:
    src: "/tmp/matomo_latest.zip"
    dest: "{{ addons_dir }}"
    remote_src: yes
    creates: "{{ addons_dir }}/matomo"
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  when: not (matomo_config_check.results | map(attribute='stat.exists') | select('true') | list | length > 0)
  tags: matomo

- name: Delete the unzipped "How to install Matomo.html" file
  file:
    path: "{{ addons_dir }}/How to install Matomo.html"
    state: absent
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  when: not (matomo_config_check.results | map(attribute='stat.exists') | select('true') | list | length > 0)
  tags: matomo

- name: Set ownership of Matomo files
  file:
    path: "{{ addons_dir }}/matomo"
    owner: "{{ matomo_owner }}"
    group: "{{ matomo_group }}"
    recurse: yes
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Ensure correct permissions on Matomo directory
  file:
    path: "{{ addons_dir }}/matomo"
    mode: '0755'
    recurse: yes
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Create Matomo database
  mysql_db:
    name: "{{ matomo_db_name }}"
    state: present
    login_host: "{{ site_env.db_host }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  when: matomo_db.changed
  tags: matomo

- name: Create Matomo database user and grant permissions
  mysql_user:
    name: "{{ item.value.matomo.db.user }}"
    password: "{{ item.value.matomo.db.password }}"
    host: "{{ site_env.db_user_host }}"
    append_privs: yes
    priv: "{{ matomo_db_name }}.*:ALL"
    state: present
    login_host: "{{ site_env.db_host }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  with_dict: "{{ combined_wordpress_sites }}"
  no_log: true
  when: matomo_db.changed
  tags: matomo

- name: Create symlink to Matomo
  file:
    path: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/{{ item.value.public_path | default('web') }}/{{ matomo_dir }}"
    src: "{{ addons_dir }}/matomo"
    state: link
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Explain next steps
  pause:
    seconds: 0
    prompt: |
      ======================
      If necessary, set up Matomo as follows:
      
      1) Deploy

      2) Point your browser to {{ wordpress_env_defaults.wp_home }}/{{ matomo_dir }}

      3) Proceed with the form using following credentials:
      
      Host:                 {{ site_env.db_user_host }}
      Database User:        {{ item.value.matomo.db.user }}
      Database Password:    {{ item.value.matomo.db.password }}
      Database:             {{ matomo_db_name }}
      Table Prefix:         none
      Database Engine:      MariaDB
      
      Set up your admin user.

      4) Log in to Matomo.

      5) Under Administration/System/Geolocation, download and activate the GeoIP 2 database.
      ======================
  with_dict: "{{ combined_wordpress_sites }}"
  no_log: true
  when: not (matomo_config_check.results | map(attribute='stat.exists') | select('true') | list | length > 0)
  tags: matomo
