---
- name: Install required PHP extensions for Matomo
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ matomo_php_extensions }}"
  notify: reload php-fpm

- name: Install PyMySQL
  apt:
    name: python3-pymysql
    state: present
  become: yes

- name: Create addons folder for Matomo installation
  file:
    path: "{{ addons_dir }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
  with_dict: "{{ wordpress_sites }}"
  no_log: true

- name: Download Matomo
  get_url:
    url: "{{ matomo_url }}"
    dest: "/tmp/matomo_latest.zip"

- name: Unzip Matomo
  unarchive:
    src: "/tmp/matomo_latest.zip"
    dest: "{{ addons_dir }}"
    remote_src: yes
    creates: "{{ addons_dir }}/{{ matomo_dir }}"
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Delete the unzipped "How to install Matomo.html" file
  file:
    path: "{{ addons_dir }}/How to install Matomo.html"
    state: absent
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Set ownership of Matomo files
  file:
    path: "{{ addons_dir }}/{{ matomo_dir }}"
    owner: "{{ matomo_owner }}"
    group: "{{ matomo_group }}"
    recurse: yes
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Ensure correct permissions on Matomo directory
  file:
    path: "{{ addons_dir }}/{{ matomo_dir }}"
    mode: '0755'
    recurse: yes
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Check if Matomo variables are set for each site
  fail:
    msg: "Matomo database credentials are not set in your group_vars – please review and ensure these are configured for the site {{ item.key }}."
  when: 
    - item.value.matomo is not defined
    - item.value.matomo.db is not defined
    - item.value.matomo.db.user is not defined or item.value.matomo.db.password is not defined
  with_dict: "{{ combined_wordpress_sites }}"
  tags: matomo

- name: Create Matomo database
  mysql_db:
    name: "{{ matomo_db_name }}"
    state: present
    login_host: "{{ site_env.db_host }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  with_dict: "{{ wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Create Matomo database user and grant permissions
  mysql_user:
    name: "{{ item.value.matomo.db.user }}"
    password: "{{ item.value.matomo.db.password }}"
    host: "{{ site_env.db_user_host }}"
    append_privs: yes
    priv: "{{ matomo_db_name }}.*:ALL"
    state: present
    login_host: "{{ site_env.db_host }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    column_case_sensitive: true
  with_dict: "{{ combined_wordpress_sites }}"
  no_log: true
  tags: matomo

- name: Create symlink to Matomo
  file:
    path: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/{{ item.value.public_path | default('web') }}/{{ item.value.matomo.path | default('matomo') }}"
    src: "{{ addons_dir }}/{{ matomo_dir }}"
    state: link
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Explain next steps
  pause:
    seconds: 0
    prompt: |
      ======================
      If necessary, set up Matomo as follows:

      1) Deploy

      2) Point your browser to {{ wordpress_env_defaults.wp_home }}/{{ item.value.matomo.path | default('matomo') }}

      3) Proceed with the form using following credentials:
      
      Host:                 {{ site_env.db_user_host }}
      Database User:        {{ item.value.matomo.db.user }}
      Database Password:    {{ item.value.matomo.db.password }}
      Database:             {{ matomo_db_name }}
      Table Prefix:         none
      Database Engine:      MariaDB
      
      Set up your admin user.

      4) Log in to Matomo.

      5) Under Administration/System/Geolocation, download and activate the GeoIP 2 database.
      ======================
  with_dict: "{{ combined_wordpress_sites }}"
  no_log: true
  tags: matomo
